[package]
name = "socket"
version = "0.1.0"
edition = "2024"

[dependencies]
tracing-subscriber = "0.3"
tower = "0.4"
socketioxide = { version = "0.8", features = ["state"] }
tracing = "0.1"
axum = "0.6"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1", features = ["full"] }
tower-http = { version = "0.4", features = ["cors"] }
chrono = { version = "0.4", features = ["serde"] }
